% setup path
addpath("Agents\", "Lane Scenarios\", "LCC\", "RL_Environments\", ...
         "Scripts\", "Scripts\Visualization\", "Plants\", "DataDictionaries\", ...
         "Scripts\Initialization\")

% 