function [scenario, roadCenters, egoVehicle] = large_OvalTrack()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 25.2 (R2025b) and Automated Driving Toolbox 25.2 (R2025b).
% Generated on: 18-Sep-2026 12:41:11

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-200 -300 0;
    0 -315 0;
    200 -300 0;
    400 -200 0;
    500 0 0;
    400 200 0;
    200 300 0;
    0 315 0;
    -200 300 0;
    -400 200 0;
    -500 0 0;
    -400 -200 0;
    -200 -300 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [0 -316.8 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [0.066 0.443 0.745], ...
    'Name', 'Car');

