function [scenario, sensor, allData] = leftCurv()
%leftCurv - Returns sensor detections
%    allData = leftCurv returns sensor detections in a structure
%    with time for an internally defined scenario and sensor suite.
%
%    [allData, scenario, sensors] = leftCurv optionally returns
%    the drivingScenario and detection generator objects.

% Generated by MATLAB(R) 25.2 (R2025b) and Automated Driving Toolbox 25.2 (R2025b).
% Generated on: 18-Sep-2026 12:41:59

% Create the drivingScenario object and ego car
[scenario, egoVehicle] = createDrivingScenario;

% Create all the sensors
sensor = createSensor(scenario);

% Add sensor to scenario
addSensors(scenario, sensor, egoVehicle.ActorID);

allData = struct('Time', {}, 'ActorPoses', {}, 'ObjectDetections', {}, 'LaneDetections', {}, 'PointClouds', {}, 'INSMeasurements', {});
time  = scenario.SimulationTime;

if ~isa(sensor,'insSensor')
    poses = targetPoses(scenario,sensor.SensorIndex);
end
% Generate the ego vehicle lane boundaries
if isa(sensor, 'visionDetectionGenerator')
    maxLaneDetectionRange = min(500,sensor.MaxRange);
    lanes = laneBoundaries(egoVehicle, 'XDistance', linspace(-maxLaneDetectionRange, maxLaneDetectionRange, 101));
end
% Generate detections for the sensor
objectDetections = {};
ptClouds = [];
insMeas = [];
[laneDetections, ~, isValidLaneTime] = sensor(lanes, time);

% Aggregate all detections into a structure for later use
if isValidLaneTime
    allData(end + 1) = struct( ...
        'Time',       scenario.SimulationTime, ...
        'ActorPoses', actorPoses(scenario), ...
        'ObjectDetections', {objectDetections}, ...
        'LaneDetections', {laneDetections}, ...
        'PointClouds',   {ptClouds}, ...
        'INSMeasurements',   {insMeas});
end

% Release the sensor object so it can be used again.
release(sensor);

%%%%%%%%%%%%%%%%%%%%
% Helper functions %
%%%%%%%%%%%%%%%%%%%%

% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

function sensor = createSensor(scenario)
% createSensors Returns all sensor objects to generate detections

% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);
sensor = visionDetectionGenerator('SensorIndex', 1, ...
    'UpdateInterval', 0.05, ...
    'SensorLocation', [1.9 0], ...
    'DetectorOutput', 'Lanes only', ...
    'Intrinsics', cameraIntrinsics([800 799.999999999999],[320 240],[480 640]), ...
    'ActorProfiles', profiles);

function [scenario, egoVehicle] = createDrivingScenario
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Construct a drivingScenario object.
scenario = drivingScenario('StopTime', 1000);

% Add all road segments
roadCenters = [-52 1.4 0;
    105 34.1 0;
    146.3 90.9 0;
    156.6 188.5 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-49.7885008262962 -0.409205227211152 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [0.066 0.443 0.745], ...
    'Name', 'Car');

