function [scenario, egoVehicle] = longStraight()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 25.2 (R2025b) and Automated Driving Toolbox 25.2 (R2025b).
% Generated on: 18-Sep-2026 13:05:32

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-0.13 -0.04 0;
    550.2 0.1 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [1.15 -2.5 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [0.066 0.443 0.745], ...
    'Name', 'Car');

