function [scenario, roadCenters, egoVehicle] = small_OvalTrack()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 25.2 (R2025b) and Automated Driving Toolbox 25.2 (R2025b).
% Generated on: 18-Sep-2026 10:17:51

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-0.100000000000005 -100 0;
    49.9 -100 0;
    99.9 -75 0;
    124.9 -0.300000000000001 0;
    99.9 75 0;
    49.9 100 0;
    -0.100000000000005 100 0;
    -50.1 75 0;
    -75.1 -0.300000000000001 0;
    -50.1 -75 0;
    -0.100000000000005 -100 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road4');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [19.8 -104.3 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [0.066 0.443 0.745], ...
    'Name', 'Car');

